/*
 * This Java source file was auto generated by running 'gradle buildInit --type java-library'
 * by 'Darshita' at '12/18/19 1:00 AM' with Gradle 2.14.1
 *
 * @author Darshita, @date 12/18/19 1:00 AM
 */
public class Library {
    public boolean someLibraryMethod() {
        return true;
    }
}
